# NOTE: The Dockerfile is used for GitHub Workflows for
# testing the installation scripts in different Debian environments.

FROM ghcr.io/rubyonracetracks/image-debian-<SUITE>-min-stage1

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/winner/docker-debian-install

COPY . .

RUN sudo chown -R winner:winner /home/winner/debian-tools-install && \
    cd /home/winner/debian-tools-install && ci/test
